package logic;

import java.util.Scanner;
import java.util.Arrays;
public class Step {
    private boolean skipSymbol = false;
    private int sid;
    // Step ID. The step ID of each Step is unique and is automatically generated by
    // the class Step. Starting from 1, each new Step ID will increase by 1.
    private int rowIndex;
    // Row index.
    private int columnIndex;
    // Column index.
    private int color;
    // The color of this step
    private static int stepCnt=1;
    public static void initializeStepCnt(int stepcnt){
        stepCnt= stepcnt;
    }
    // Initialized to 1, increased by 1 every time a Step object is created.
    public Step(int rowIndex, int columnIndex, int color) {
        this.sid = stepCnt;
        stepCnt++;
        this.rowIndex = rowIndex;
        this.columnIndex = columnIndex;
        this.color = color;
    }
    public Step(int sid,int rowIndex, int columnIndex, int color) {
        this.sid = sid;
        this.rowIndex = rowIndex;
        this.columnIndex = columnIndex;
        this.color = color;
    }
    // Constructor, automatically generate step ID and step object. Initialize row
    // index, column index, and color.
    public int getSid() {
        return this.sid;
    }

    public int getColor() {
        return this.color;
    }

    public void setColor(int color) {
        this.color = color;
    }

    public int getRowIndex() {
        return this.rowIndex;
    }

    public void setRowIndex(int rowIndex) {
        this.rowIndex = rowIndex;
    }

    public int getColumnIndex() {
        return this.columnIndex;
    }

    public void setColumnIndex(int columnIndex) {
        this.columnIndex = columnIndex;
    }

    public static int getStepCnt() {
        return stepCnt;
    }

    // Get the value of StepCnt
    public String toString() {
        return "sid: " + this.sid + ", rowIndex: " + this.rowIndex + ", columnIndex: " + this.columnIndex + ", color: "
                + this.color;
    }

    // When printing the row index, column index and color for an object of this
    // class, follow the format: "sid: %d, rowIndex: %d, columnIndex: %d, color: %d"
    // (without quotes)
    public static void main(String[] args) {
    }
}
